# Generated by Django 3.2.4 on 2021-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sehirmerkezi'),
    ]

    operations = [
        migrations.AddField(
            model_name='parselverileri',
            name='ParselID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
